### PR TITLE
feat: node 20 upgrade

### PR DESCRIPTION
**Pull request by orangeeli**
Node 20 upgrade

### CODE REVIEW

**Comment by frankvollebregt** [comment]
Since this repository seems quite inactive, you might want to consider using the forked version as linked in the issue here:

https://github.com/Fooji/create-aws-profile-action/issues/7#issuecomment-1933354602

Which is already available from the GH marketplace, and will hopefully be supported in the future too

**Comment by frankvollebregt** [comment]
Currently, I am using the forked version as linked in the issue here https://github.com/Fooji/create-aws-profile-action/issues/7#issuecomment-1933354602 , since this action hasn't received any marketplace updates for the past two years (notably, Node 16 support).

I see you are part of the Fooji organization... does that imply that there will be updates once again?

**Comment by williamcoates** [comment]
> Currently, I am using the forked version as linked in the issue here [#7 (comment)](https://github.com/Fooji/create-aws-profile-action/issues/7#issuecomment-1933354602) , since this action hasn't received any marketplace updates for the past two years (notably, Node 16 support).
> 
> I see you are part of the Fooji organization... does that imply that there will be updates once again?

We are using it actively in our organization, we didn't realize anyone else was using it,  apologies! We just hadn't needed to make any updates until now...

**Review by williamcoates — APPROVED** [review]

**Comment by frankvollebregt** [comment]
No need to apologize haha, we just happened upon it and it's pretty useful :)

Will you also be tagging a release for the GH marketplace? So that I can use an @ tag for this updated version (instead of using a specific commit or an `@master` tag that may change over time)

Thanks

**Pull request merged**
